version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: intu_erp_postgres
    environment:
      POSTGRES_DB: intu_erp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - intu_erp_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: intu_erp_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - intu_erp_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: intu_erp_backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:password@postgres:5432/intu_erp
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key
      JWT_EXPIRES_IN: 7d
      PORT: 3001
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - intu_erp_network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: intu_erp_frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - intu_erp_network

volumes:
  postgres_data:
  redis_data:

networks:
  intu_erp_network:
    driver: bridge
